"""baseline_schema

Revision ID: 3ab22db173a5
Revises: 
Create Date: 2026-03-20 18:52:34.212731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab22db173a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_basis_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.Enum('retell', 'openai', 'infrastructure', name='cost_basis_provider_enum'), nullable=False),
    sa.Column('cost_per_unit_cents', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('unit_type', sa.Enum('minute', '1k_tokens', 'fixed_monthly', name='cost_basis_unit_enum'), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dfy_packages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=127), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('billing_type', sa.Enum('one_time', 'recurring', 'custom_quote', name='dfy_billing_type_enum'), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=True),
    sa.Column('estimated_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('partners',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subdomain', sa.String(length=63), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', name='partner_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdomain')
    )
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.create_index('idx_partners_subdomain', ['subdomain'], unique=False)

    op.create_table('plan_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('stripe_product_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=True),
    sa.Column('price_monthly_cents', sa.Integer(), nullable=False),
    sa.Column('included_minutes', sa.Integer(), nullable=False),
    sa.Column('included_agents', sa.Integer(), nullable=False),
    sa.Column('included_numbers', sa.Integer(), nullable=False),
    sa.Column('overage_rate_cents', sa.Integer(), nullable=False),
    sa.Column('additional_number_rate_cents', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('tool_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('calendar', 'email', 'sms', 'crm_ticket', 'note_summary', 'custom_webhook', name='tool_category_enum'), nullable=False),
    sa.Column('tool_type', sa.Enum('real_time', 'post_call', name='tool_type_enum'), nullable=False),
    sa.Column('access_tier', sa.Enum('self_serve', 'dfy_only', 'admin_approved', name='access_tier_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_class', sa.String(length=100), nullable=True),
    sa.Column('default_parameters_schema', sa.JSON(), nullable=True),
    sa.Column('default_description_for_llm', sa.Text(), nullable=True),
    sa.Column('requires_oauth', sa.Boolean(), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('topup_pack_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_email', ['email'], unique=False)

    op.create_table('webhook_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=63), nullable=False),
    sa.Column('event_type', sa.String(length=127), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processed', 'failed', name='webhook_status_enum'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branding_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('support_email', sa.String(length=255), nullable=False),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partner_id')
    )
    op.create_table('partner_settlement_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_payout_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'paid', 'failed', name='settlement_status_enum'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payout_reference_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('rule_type', sa.Enum('minute_overage', 'number_overage', 'custom_feature', name='pricing_rule_type_enum'), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('direct', 'partner_originated', name='tenant_type_enum'), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', 'canceled', name='tenant_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index('idx_tenants_partner_id', ['partner_id'], unique=False)

    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('retell_agent_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending', 'active', 'failed', 'needs_attention', name='agent_status_enum'), nullable=False),
    sa.Column('mode', sa.Enum('inbound', 'outbound', name='agent_mode_enum'), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('voice_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('retell_agent_id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index('idx_agents_tenant_id', ['tenant_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=127), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_lists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_lists', schema=None) as batch_op:
        batch_op.create_index('idx_contact_lists_tenant_id', ['tenant_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('stripe_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('amount_due_cents', sa.Integer(), nullable=False),
    sa.Column('amount_paid_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'open', 'paid', 'uncollectible', 'void', name='invoice_status_enum'), nullable=False),
    sa.Column('invoice_pdf_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_invoice_id')
    )
    op.create_table('memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'viewer', 'partner', 'superadmin', name='membership_role_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', name='uq_memberships_user_tenant')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index('idx_memberships_user_tenant', ['user_id', 'tenant_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('email', 'in_app', name='notification_type_enum'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='notification_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=63), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'past_due', 'canceled', 'trialing', name='subscription_status_enum'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=True),
    sa.Column('payment_method_last4', sa.String(length=4), nullable=True),
    sa.Column('payment_method_brand', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan_definitions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('support_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('admin_user_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_tool_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('tool_template_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('connected', 'disconnected', 'error', 'needs_reconnect', name='connection_status_enum'), nullable=False),
    sa.Column('credential_mode', sa.String(length=20), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['tool_template_id'], ['tool_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'tool_template_id', name='uq_tenant_tool_connection')
    )
    with op.batch_alter_table('tenant_tool_connections', schema=None) as batch_op:
        batch_op.create_index('idx_tenant_tool_connections_tenant', ['tenant_id'], unique=False)

    op.create_table('usage_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('billing_period_start', sa.Date(), nullable=False),
    sa.Column('billing_period_end', sa.Date(), nullable=False),
    sa.Column('total_included_minutes_used', sa.Integer(), nullable=True),
    sa.Column('total_topup_minutes_used', sa.Integer(), nullable=True),
    sa.Column('total_overage_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'billing_period_start', name='uq_usage_summaries_tenant_period')
    )
    with op.batch_alter_table('usage_summaries', schema=None) as batch_op:
        batch_op.create_index('idx_usage_summaries_tenant_period', ['tenant_id', 'billing_period_start'], unique=False)

    op.create_table('agent_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('role_description', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=63), nullable=True),
    sa.Column('business_context', sa.JSON(), nullable=True),
    sa.Column('hours_of_operation', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id')
    )
    with op.batch_alter_table('agent_configs', schema=None) as batch_op:
        batch_op.create_index('idx_agent_configs_tenant_id', ['tenant_id'], unique=False)

    op.create_table('agent_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('raw_prompt', sa.Text(), nullable=False),
    sa.Column('generated_config', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending_review', 'approved', 'rejected', name='draft_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_tool_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('tool_type', sa.Enum('real_time', 'post_call', name='tool_type_enum'), nullable=False),
    sa.Column('function_name', sa.String(length=100), nullable=False),
    sa.Column('description_for_llm', sa.Text(), nullable=True),
    sa.Column('parameters_schema', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['tenant_tool_connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'function_name', name='uq_agent_tool_function')
    )
    with op.batch_alter_table('agent_tool_assignments', schema=None) as batch_op:
        batch_op.create_index('idx_agent_tool_assignments_agent', ['agent_id'], unique=False)

    op.create_table('agent_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('retell_version_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_versions', schema=None) as batch_op:
        batch_op.create_index('idx_agent_versions_tenant_id', ['tenant_id'], unique=False)

    op.create_table('call_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('retell_call_id', sa.String(length=255), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('from_number', sa.String(length=20), nullable=False),
    sa.Column('to_number', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='call_direction_enum'), nullable=False),
    sa.Column('start_timestamp', sa.DateTime(), nullable=True),
    sa.Column('end_timestamp', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=63), nullable=True),
    sa.Column('disconnection_reason', sa.String(length=255), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=63), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('retell_cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('recording_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('retell_call_id')
    )
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.create_index('idx_call_logs_agent_id', ['agent_id'], unique=False)
        batch_op.create_index('idx_call_logs_tenant_id', ['tenant_id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('contact_list_id', sa.String(length=36), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=63), nullable=True),
    sa.Column('dynamic_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('active', 'opted_out', 'invalid_number', name='contact_status_enum'), nullable=False),
    sa.Column('opted_out_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_list_id'], ['contact_lists.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_list_id', 'phone_number', name='uq_contacts_list_phone')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index('idx_contacts_phone_number', ['phone_number'], unique=False)
        batch_op.create_index('idx_contacts_tenant_id', ['tenant_id'], unique=False)

    op.create_table('dfy_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('intake', 'pending_payment', 'in_progress', 'in_review', 'completed', 'canceled', name='dfy_project_status_enum'), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('intake_form_data', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('quoted_price_cents', sa.Integer(), nullable=True),
    sa.Column('max_revisions', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.String(length=255), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('target_delivery_date', sa.Date(), nullable=True),
    sa.Column('revision_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['dfy_packages.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guardrail_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('prohibited_topic', sa.String(length=512), nullable=False),
    sa.Column('fallback_message', sa.String(length=512), server_default='I cannot discuss that topic.', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guardrail_rules', schema=None) as batch_op:
        batch_op.create_index('idx_guardrail_rules_tenant_id', ['tenant_id'], unique=False)

    op.create_table('handoff_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('condition', sa.String(length=512), nullable=False),
    sa.Column('destination_number', sa.String(length=20), nullable=True),
    sa.Column('transfer_message', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('handoff_rules', schema=None) as batch_op:
        batch_op.create_index('idx_handoff_rules_tenant_id', ['tenant_id'], unique=False)

    op.create_table('knowledge_base_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('text', 'url', 'file', 'faq', name='kb_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('retell_kb_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('succeeded', 'failed', 'refunded', 'partially_refunded', 'disputed', name='payment_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_intent_id')
    )
    op.create_table('phone_numbers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('retell_number_id', sa.String(length=255), nullable=True),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('active', 'unassigned', 'pending_provision', 'failed', name='phone_number_status_enum'), nullable=False),
    sa.Column('area_code', sa.String(length=10), nullable=True),
    sa.Column('friendly_name', sa.String(length=255), nullable=True),
    sa.Column('monthly_cost_cents', sa.Integer(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('retell_number_id')
    )
    with op.batch_alter_table('phone_numbers', schema=None) as batch_op:
        batch_op.create_index('idx_phone_numbers_tenant_id', ['tenant_id'], unique=False)

    op.create_table('workflow_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trigger_condition', sa.String(length=512), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_definitions', schema=None) as batch_op:
        batch_op.create_index('idx_workflow_definitions_tenant_id', ['tenant_id'], unique=False)

    op.create_table('action_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('call_log_id', sa.String(length=36), nullable=True),
    sa.Column('assignment_id', sa.String(length=36), nullable=True),
    sa.Column('tool_type', sa.Enum('real_time', 'post_call', name='tool_type_enum'), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('success', 'failed', 'retrying', name='action_log_status_enum'), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.String(length=100), nullable=True),
    sa.Column('execution_ms', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('credential_source', sa.String(length=20), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['assignment_id'], ['agent_tool_assignments.id'], ),
    sa.ForeignKeyConstraint(['call_log_id'], ['call_logs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.create_index('idx_action_logs_agent', ['agent_id'], unique=False)
        batch_op.create_index('idx_action_logs_call', ['call_log_id'], unique=False)
        batch_op.create_index('idx_action_logs_idempotency', ['idempotency_key'], unique=False)
        batch_op.create_index('idx_action_logs_tenant', ['tenant_id'], unique=False)

    op.create_table('additional_number_charges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('phone_number_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('charge_amount_cents', sa.Integer(), nullable=False),
    sa.Column('billing_period_start', sa.Date(), nullable=False),
    sa.Column('billing_period_end', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('contact_list_id', sa.String(length=36), nullable=False),
    sa.Column('caller_id_number_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'running', 'paused', 'completed', 'canceled', name='campaign_status_enum'), nullable=False),
    sa.Column('retell_batch_call_id', sa.String(length=255), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('window_start_min', sa.Integer(), nullable=True),
    sa.Column('window_end_min', sa.Integer(), nullable=True),
    sa.Column('allowed_days', sa.JSON(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('total_tasks', sa.Integer(), nullable=True),
    sa.Column('completed_tasks', sa.Integer(), nullable=True),
    sa.Column('failed_tasks', sa.Integer(), nullable=True),
    sa.Column('launched_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['caller_id_number_id'], ['phone_numbers.id'], ),
    sa.ForeignKeyConstraint(['contact_list_id'], ['contact_lists.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index('idx_campaigns_status', ['status'], unique=False)
        batch_op.create_index('idx_campaigns_tenant_id', ['tenant_id'], unique=False)

    op.create_table('dfy_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('is_revision_request', sa.Boolean(), nullable=True),
    sa.Column('is_admin_note', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['dfy_projects.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('minute_topup_purchases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=True),
    sa.Column('minutes_added', sa.Integer(), nullable=False),
    sa.Column('minutes_remaining', sa.Integer(), nullable=False),
    sa.Column('purchase_price_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recording_metadata',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('call_log_id', sa.String(length=36), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('recording_url', sa.String(length=512), nullable=True),
    sa.Column('is_sensitive_redacted', sa.Boolean(), nullable=True),
    sa.Column('call_analysis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_log_id'], ['call_logs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_log_id')
    )
    with op.batch_alter_table('recording_metadata', schema=None) as batch_op:
        batch_op.create_index('idx_recording_metadata_tenant_id', ['tenant_id'], unique=False)

    op.create_table('revenue_ledger_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=True),
    sa.Column('source_type', sa.Enum('subscription', 'top_up', 'overage', 'setup_fee', 'refund', 'dispute', name='ledger_source_type_enum'), nullable=False),
    sa.Column('gross_amount_cents', sa.Integer(), nullable=False),
    sa.Column('net_eligible_amount_cents', sa.Integer(), nullable=False),
    sa.Column('platform_share_cents', sa.Integer(), nullable=False),
    sa.Column('partner_share_cents', sa.Integer(), nullable=False),
    sa.Column('eligibility_status', sa.Enum('pending', 'eligible', 'voided', 'settled', name='eligibility_status_enum'), nullable=False),
    sa.Column('eligible_on_date', sa.Date(), nullable=True),
    sa.Column('settlement_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['partner_settlement_records.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revenue_ledger_entries', schema=None) as batch_op:
        batch_op.create_index('idx_ledger_partner_status', ['partner_id', 'eligibility_status'], unique=False)

    op.create_table('usage_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('call_log_id', sa.String(length=36), nullable=False),
    sa.Column('provider_reported_seconds', sa.Integer(), nullable=False),
    sa.Column('internally_billable_seconds', sa.Integer(), nullable=False),
    sa.Column('reconciliation_status', sa.Enum('matched', 'adjusted', 'disputed', name='reconciliation_status_enum'), nullable=False),
    sa.Column('adjustment_reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_log_id'], ['call_logs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_log_id')
    )
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.create_index('idx_usage_records_tenant_id', ['tenant_id'], unique=False)

    op.create_table('campaign_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'queued', 'calling', 'completed', 'failed', 'skipped', name='task_status_enum'), nullable=False),
    sa.Column('disposition', sa.Enum('completed', 'voicemail', 'no_answer', 'invalid_number', 'opted_out', 'error', name='task_disposition_enum'), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('call_log_id', sa.String(length=36), nullable=True),
    sa.Column('retell_task_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('last_attempted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_log_id'], ['call_logs.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_tasks', schema=None) as batch_op:
        batch_op.create_index('idx_campaign_tasks_campaign_id', ['campaign_id'], unique=False)
        batch_op.create_index('idx_campaign_tasks_status', ['status'], unique=False)

    op.create_table('payout_line_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('settlement_id', sa.String(length=36), nullable=False),
    sa.Column('ledger_entry_id', sa.String(length=36), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['revenue_ledger_entries.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['partner_settlement_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ledger_entry_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payout_line_items')
    with op.batch_alter_table('campaign_tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_campaign_tasks_status')
        batch_op.drop_index('idx_campaign_tasks_campaign_id')

    op.drop_table('campaign_tasks')
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_index('idx_usage_records_tenant_id')

    op.drop_table('usage_records')
    with op.batch_alter_table('revenue_ledger_entries', schema=None) as batch_op:
        batch_op.drop_index('idx_ledger_partner_status')

    op.drop_table('revenue_ledger_entries')
    with op.batch_alter_table('recording_metadata', schema=None) as batch_op:
        batch_op.drop_index('idx_recording_metadata_tenant_id')

    op.drop_table('recording_metadata')
    op.drop_table('minute_topup_purchases')
    op.drop_table('dfy_messages')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index('idx_campaigns_tenant_id')
        batch_op.drop_index('idx_campaigns_status')

    op.drop_table('campaigns')
    op.drop_table('additional_number_charges')
    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_action_logs_tenant')
        batch_op.drop_index('idx_action_logs_idempotency')
        batch_op.drop_index('idx_action_logs_call')
        batch_op.drop_index('idx_action_logs_agent')

    op.drop_table('action_logs')
    with op.batch_alter_table('workflow_definitions', schema=None) as batch_op:
        batch_op.drop_index('idx_workflow_definitions_tenant_id')

    op.drop_table('workflow_definitions')
    with op.batch_alter_table('phone_numbers', schema=None) as batch_op:
        batch_op.drop_index('idx_phone_numbers_tenant_id')

    op.drop_table('phone_numbers')
    op.drop_table('payments')
    op.drop_table('knowledge_base_items')
    with op.batch_alter_table('handoff_rules', schema=None) as batch_op:
        batch_op.drop_index('idx_handoff_rules_tenant_id')

    op.drop_table('handoff_rules')
    with op.batch_alter_table('guardrail_rules', schema=None) as batch_op:
        batch_op.drop_index('idx_guardrail_rules_tenant_id')

    op.drop_table('guardrail_rules')
    op.drop_table('dfy_projects')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index('idx_contacts_tenant_id')
        batch_op.drop_index('idx_contacts_phone_number')

    op.drop_table('contacts')
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_call_logs_tenant_id')
        batch_op.drop_index('idx_call_logs_agent_id')

    op.drop_table('call_logs')
    with op.batch_alter_table('agent_versions', schema=None) as batch_op:
        batch_op.drop_index('idx_agent_versions_tenant_id')

    op.drop_table('agent_versions')
    with op.batch_alter_table('agent_tool_assignments', schema=None) as batch_op:
        batch_op.drop_index('idx_agent_tool_assignments_agent')

    op.drop_table('agent_tool_assignments')
    op.drop_table('agent_drafts')
    with op.batch_alter_table('agent_configs', schema=None) as batch_op:
        batch_op.drop_index('idx_agent_configs_tenant_id')

    op.drop_table('agent_configs')
    with op.batch_alter_table('usage_summaries', schema=None) as batch_op:
        batch_op.drop_index('idx_usage_summaries_tenant_period')

    op.drop_table('usage_summaries')
    with op.batch_alter_table('tenant_tool_connections', schema=None) as batch_op:
        batch_op.drop_index('idx_tenant_tool_connections_tenant')

    op.drop_table('tenant_tool_connections')
    op.drop_table('support_notes')
    op.drop_table('subscriptions')
    op.drop_table('organizations')
    op.drop_table('notifications')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index('idx_memberships_user_tenant')

    op.drop_table('memberships')
    op.drop_table('invoices')
    with op.batch_alter_table('contact_lists', schema=None) as batch_op:
        batch_op.drop_index('idx_contact_lists_tenant_id')

    op.drop_table('contact_lists')
    op.drop_table('audit_logs')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index('idx_agents_tenant_id')

    op.drop_table('agents')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index('idx_tenants_partner_id')

    op.drop_table('tenants')
    op.drop_table('pricing_rules')
    op.drop_table('partner_settlement_records')
    op.drop_table('branding_settings')
    op.drop_table('webhook_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_email')

    op.drop_table('users')
    op.drop_table('topup_pack_definitions')
    op.drop_table('tool_templates')
    op.drop_table('platform_settings')
    op.drop_table('plan_definitions')
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index('idx_partners_subdomain')

    op.drop_table('partners')
    op.drop_table('dfy_packages')
    op.drop_table('cost_basis_settings')
    # ### end Alembic commands ###
